import { Property } from './types';

const defaultCatalog: Property[] = [
  {
    id: "PJ-PROP-001",
    title: "The Grand Junction Towers",
    location: "MM City, Shilphata, Navi Mumbai Side",
    bhk: 2,
    type: "Under Construction",
    price: "₹48.5 Lakhs onwards",
    priceNumeric: 4850050,
    carpetArea: "685 Sq.Ft - 795 Sq.Ft",
    sizeSqFt: 740,
    brokerage: "0%",
    paymentPlan: "20:80 Builder Subvention",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&q=80&w=600",
    tag: "Vests Structured Savings",
    highlights: ["Strategic Shilphata Junction Connectivity", "Modern Club House", "Next to Proposed Metro", "RERA Registered Project", "Verified 20:80 Payment Terms"],
    purpose: "Buy",
    propertyType: "Apartment",
    bathrooms: 2,
    furnishing: "Semi",
    buildingType: "Gated Community",
    floorLevel: "Mid",
    viewType: "City",
    rentalFrequency: "N/A",
    paymentTerms: "N/A",
    availability: "Available",
    verified: true,
    featured: true,
    description: "Centrally positioned premium towers with best-in-class multi-modal transit connectivity to Navi Mumbai and Thane.",
    detailedDescription: "The Grand Junction Towers is an emblem of modern high-rise living strategically located to unify convenience and comfort. Surrounded by rapid infrastructural developments and close to the proposed metro line, these homes offer amazing appreciation potential. Designed for those seeking high-quality construction paired with top-of-the-line amenities such as a state-of-the-art gymnasium, an expansive clubhouse, and 24/7 security surveillance.",
    amenities: ["Parking", "Balcony", "Central AC", "Gym", "Pool", "Security", "Kids Play Area", "Power Backup"],
    floorPlanImage: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&q=80&w=600",
    brochureUrl: "#download-brochure-pdf",
    titleDeedUrl: "#view-title-deed-verification",
    agentName: "Rajesh K. Sharma",
    agentRole: "Principal Advisor",
    agentPhone: "+91 86686 44479",
    agentEmail: "rajesh@propertyjunction.co",
    agentWhatsApp: "https://wa.me/918668644479?text=Hi%20Rajesh,%20I%20am%20interested%20in%20The%20Grand%20Junction%20Towers%20(PJ-PROP-001)",
    agentPhoto: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&q=80&w=400",
    gallery: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=800"
    ]
  },
  {
    id: "PJ-PROP-002",
    title: "Signature Heights Elite",
    location: "Sector 20, Kharghar, Navi Mumbai",
    bhk: 3,
    type: "Ready to Move",
    price: "₹1.45 Crore onwards",
    priceNumeric: 14500000,
    carpetArea: "1,150 Sq.Ft - 1,420 Sq.Ft",
    sizeSqFt: 1320,
    brokerage: "0%",
    paymentPlan: "Immediate Register-Move In",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=600",
    tag: "High Rental Yield Ready",
    highlights: ["Overlooking Kharghar Hills Skyline", "Double-Height Designer Lobby", "No Commission / 0% Fees", "Occupancy Certificate (OC) Received", "Perfect Investor Rental Asset"],
    purpose: "Buy",
    propertyType: "Apartment",
    bathrooms: 3,
    furnishing: "Furnished",
    buildingType: "Building",
    floorLevel: "High",
    viewType: "Sea",
    rentalFrequency: "N/A",
    paymentTerms: "N/A",
    availability: "Ready",
    verified: true,
    featured: true,
    description: "Majestic hill-facing executive home equipped with bespoke furnishings and state-of-the-art marble design layouts.",
    detailedDescription: "This ultra-luxurious development is custom-tailored for families looking for high-class urban elegance in Kharghar. Signature Heights Elite towers offer pristine hill views, double-height designer entrance lobbies, premium high-speed elevators, and a gorgeous swimming pool. Ready-to-move-in status ensures you do not wait for your home of dreams.",
    amenities: ["Parking", "Balcony", "Central AC", "Gym", "Pool", "Security", "Intercom", "Elevators", "Club House"],
    floorPlanImage: "https://images.unsplash.com/photo-1545464693-f1798a373343?auto=format&fit=crop&q=80&w=600",
    brochureUrl: "#download-brochure-pdf",
    titleDeedUrl: "#view-title-deed-verification",
    agentName: "Aarti S. Mehta",
    agentRole: "Kharghar Territory Lead",
    agentPhone: "+91 86686 44479",
    agentEmail: "aarti@propertyjunction.co",
    agentWhatsApp: "https://wa.me/918668644479?text=Hi%20Aarti,%20I%20am%20interested%20in%20Signature%20Heights%20Elite%20(PJ-PROP-002)",
    agentPhoto: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400",
    gallery: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&q=80&w=800"
    ]
  },
  {
    id: "PJ-PROP-003",
    title: "MM Pristine Flats",
    location: "Shilphata-Mumbra Highway Corridor, Thane Side",
    bhk: 1,
    type: "Under Construction",
    price: "₹34.8 Lakhs onwards",
    priceNumeric: 3480000,
    carpetArea: "420 Sq.Ft - 490 Sq.Ft",
    sizeSqFt: 460,
    brokerage: "0%",
    paymentPlan: "20:80 Scheme Authorized",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=600",
    tag: "Budget Friendly Premium",
    highlights: ["Extremely Low Maintenance Costs", "24 Hours Active Gated Estate", "Zero Brokerage Fees", "High ROI Potential", "Vetted Bank Loans Authorized"],
    purpose: "Buy",
    propertyType: "Apartment",
    bathrooms: 1,
    furnishing: "Unfurnished",
    buildingType: "Gated Community",
    floorLevel: "Low",
    viewType: "Garden",
    rentalFrequency: "N/A",
    paymentTerms: "N/A",
    availability: "Available",
    verified: true,
    featured: false,
    description: "Affordable luxury nestled within nature with zero compromises on quality, security, and smart space planning.",
    detailedDescription: "Designed specifically for first-time homebuyers and smart investors, MM Pristine Flats offers premium construction quality on highly reasonable rates. Positioned on the rapidly growing Shilphata-Mumbra corridor, these homes grant unmatched access to central arterial highways.",
    amenities: ["Parking", "Balcony", "Security", "Power Backup", "Kids Play Area", "Jogging Track"],
    floorPlanImage: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&q=80&w=600",
    brochureUrl: "#download-brochure-pdf",
    titleDeedUrl: "#view-title-deed-verification",
    agentName: "Karan Johar",
    agentRole: "Senior Relationship Officer",
    agentPhone: "+91 86686 44479",
    agentEmail: "karan@propertyjunction.co",
    agentWhatsApp: "https://wa.me/918668644479?text=Hi%20Karan,%20I%20am%20interested%20in%20MM%20Pristine%20Flats%20(PJ-PROP-003)",
    agentPhoto: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400",
    gallery: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&q=80&w=800"
    ]
  },
  {
    id: "PJ-PROP-004",
    title: "Thane Imperial Deck",
    location: "Thane West, Maharashtra",
    bhk: 3,
    type: "Ready to Move",
    price: "₹1.95 Crore onwards",
    priceNumeric: 19500000,
    carpetArea: "1,280 Sq.Ft - 1,650 Sq.Ft",
    sizeSqFt: 1510,
    brokerage: "0%",
    paymentPlan: "Flexible Ready Option",
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&q=80&w=600",
    tag: "Limited Deck Collection",
    highlights: ["Exquisite Glass Panoramic Balcony", "Premium Marble Carpeting", "Direct Paperwork Handled by Agency", "Zero Stamp Duty Promotion Weeks", "Elite Club & Pool Access"],
    purpose: "Buy",
    propertyType: "Apartment",
    bathrooms: 3,
    furnishing: "Semi",
    buildingType: "Building",
    floorLevel: "High",
    viewType: "Sea",
    rentalFrequency: "N/A",
    paymentTerms: "N/A",
    availability: "Ready",
    verified: true,
    featured: true,
    description: "Unrivaled architectural masterpiece boasting premium glass panoramic decks and ultra-high-end marble construction.",
    detailedDescription: "For the discerning few who settle for nothing but perfection, Thane Imperial Deck presents custom glass balconies overlooking pristine horizons. Handcrafted premium marble, automated internal lightning systems, and curated designer fittings define this top-level landmark.",
    amenities: ["Parking", "Balcony", "Central AC", "Gym", "Pool", "Security", "Steam & Sauna", "Billiards Room", "Valet Parking"],
    floorPlanImage: "https://images.unsplash.com/photo-1545464693-f1798a373343?auto=format&fit=crop&q=80&w=600",
    brochureUrl: "#download-brochure-pdf",
    titleDeedUrl: "#view-title-deed-verification",
    agentName: "Aarti S. Mehta",
    agentRole: "Thane Premium Advisor",
    agentPhone: "+91 86686 44479",
    agentEmail: "aarti@propertyjunction.co",
    agentWhatsApp: "https://wa.me/918668644479?text=Hi%20Aarti,%20I%20am%20interested%20in%20Thane%20Imperial%20Deck%20(PJ-PROP-004)",
    agentPhoto: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400",
    gallery: [
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&q=80&w=800"
    ]
  },
  {
    id: "PJ-PROP-005",
    title: "The Oasis Gardens",
    location: "Sector 12, Kharghar Bypass, Navi Mumbai",
    bhk: 2,
    type: "Under Construction",
    price: "₹82.5 Lakhs onwards",
    priceNumeric: 8250000,
    carpetArea: "710 Sq.Ft - 860 Sq.Ft",
    sizeSqFt: 810,
    brokerage: "0%",
    paymentPlan: "10:90 / 20:80 Managed Plans",
    image: "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&q=80&w=600",
    tag: "High Capital Appreciation",
    highlights: ["Surrounded by Lush Organic Parks", "Smart Automation Enabled", "Exclusive Dealership Agency Rights", "0% Brokerage Charged", "Excellent School Proximity"],
    purpose: "Buy",
    propertyType: "Apartment",
    bathrooms: 2,
    furnishing: "Semi",
    buildingType: "Gated Community",
    floorLevel: "Mid",
    viewType: "Garden",
    rentalFrequency: "N/A",
    paymentTerms: "N/A",
    availability: "Available",
    verified: true,
    featured: false,
    description: "An eco-conscious living concept featuring vast bio-organic lawns, smart features, and elite community specifications.",
    detailedDescription: "The Oasis Gardens is synonymous with green living. Designed to lower your carbon print while maintaining an opulent lifestyle, this residential landscape features multi-tiered organic rooftop parks, gray-water harvesting, and continuous smart home system sensors.",
    amenities: ["Parking", "Balcony", "Gym", "Pool", "Security", "Organic Gardens", "Walking Trails", "Solar Power Grid"],
    floorPlanImage: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&q=80&w=600",
    brochureUrl: "#download-brochure-pdf",
    titleDeedUrl: "#view-title-deed-verification",
    agentName: "Rajesh K. Sharma",
    agentRole: "Principal Advisor",
    agentPhone: "+91 86686 44479",
    agentEmail: "rajesh@propertyjunction.co",
    agentWhatsApp: "https://wa.me/918668644479?text=Hi%20Rajesh,%20I%20am%20interested%20in%20The%20Oasis%20Gardens%20(PJ-PROP-005)",
    agentPhoto: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&q=80&w=400",
    gallery: [
      "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=800"
    ]
  },
  {
    id: "PJ-PROP-006",
    title: "Royal Palms Estate Villa",
    location: "Sector 3, Kharghar Hills, Navi Mumbai",
    bhk: 4,
    type: "Ready to Move",
    price: "₹3.80 Crore onwards",
    priceNumeric: 38000000,
    carpetArea: "3,200 Sq.Ft - 4,100 Sq.Ft",
    sizeSqFt: 3600,
    brokerage: "0%",
    paymentPlan: "Custom VIP Instalments Authorized",
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&q=80&w=600",
    tag: "Ultra Luxury Estate Collection",
    highlights: ["Individual Private Plunge Pool", "Exotic Private Botanical Garden", "Gated Ultra-Secure Elite Compound", "Exclusive Concierge Services Available", "Verified Clear Title Verification"],
    purpose: "Buy",
    propertyType: "Villa",
    bathrooms: 4,
    furnishing: "Furnished",
    buildingType: "Villa",
    floorLevel: "High",
    viewType: "Garden",
    rentalFrequency: "N/A",
    paymentTerms: "N/A",
    availability: "Available",
    verified: true,
    featured: true,
    description: "An extraordinary multi-generational private villa featuring bespoke Italian marble, security details, and a plunge pool.",
    detailedDescription: "For those requesting the pinnacle of custom isolation and design, the Royal Palms Estate Villa stands in general grandeur. Spanning across massive multi-level structures, featuring standard smart automation, security alarms, a dedicated resident lift, and personal parking for up to 4 sedans.",
    amenities: ["Parking", "Balcony", "Central AC", "Gym", "Pool", "Security", "Private Pool", "Private Garden", "Home Automation System"],
    floorPlanImage: "https://images.unsplash.com/photo-1545464693-f1798a373343?auto=format&fit=crop&q=80&w=600",
    brochureUrl: "#download-brochure-pdf",
    titleDeedUrl: "#view-title-deed-verification",
    agentName: "Aarti S. Mehta",
    agentRole: "Special Portfolio Lead",
    agentPhone: "+91 86686 44479",
    agentEmail: "aarti@propertyjunction.co",
    agentWhatsApp: "https://wa.me/918668644479?text=Hi%20Aarti,%20I%20am%20interested%20in%20Royal%20Palms%20Estate%20Villa%20(PJ-PROP-006)",
    agentPhoto: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400",
    gallery: [
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800"
    ]
  },
  {
    id: "PJ-PROP-007",
    title: "Signature Townhouse Plaza",
    location: "Mumbra Highway Bypass Corridor, Thane Side",
    bhk: 3,
    type: "Under Construction",
    price: "₹1.15 Crore onwards",
    priceNumeric: 11500000,
    carpetArea: "1,850 Sq.Ft",
    sizeSqFt: 1850,
    brokerage: "0%",
    paymentPlan: "40:60 Builder-Linked Scheme",
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&q=80&w=600",
    tag: "High Appreciation Suburb",
    highlights: ["Individual Multi-Car Private Garage", "Continuous Multi-Tier Gated Security", "Zero Commission / Direct Booking", "Proximity to Upcoming High-Speed Monorail", "Exclusive Rooftop Barbecue Deck"],
    purpose: "Buy",
    propertyType: "Townhouse",
    bathrooms: 3,
    furnishing: "Semi",
    buildingType: "Gated Community",
    floorLevel: "Low",
    viewType: "Community",
    rentalFrequency: "N/A",
    paymentTerms: "N/A",
    availability: "Coming Soon",
    verified: true,
    featured: false,
    description: "Multi-tiered dynamic modern townhouse layouts providing maximum independent space comfort and family-centric communities.",
    detailedDescription: "This premium community complex provides the dynamic balance of independent house features with gated apartment luxury perks. Incorporating individual layout configurations, solar system lines, private high-velocity garages, and an iconic landscape park system surrounding your family.",
    amenities: ["Parking", "Balcony", "Gym", "Pool", "Security", "Garages", "Barbecue Deck", "Club House"],
    floorPlanImage: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&q=80&w=600",
    brochureUrl: "#download-brochure-pdf",
    titleDeedUrl: "#view-title-deed-verification",
    agentName: "Karan Johar",
    agentRole: "Senior Relationship Officer",
    agentPhone: "+91 86686 44479",
    agentEmail: "karan@propertyjunction.co",
    agentWhatsApp: "https://wa.me/918668644479?text=Hi%20Karan,%20I%20am%20interested%20in%20Signature%20Townhouse%20Plaza%20(PJ-PROP-007)",
    agentPhoto: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400",
    gallery: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-160066753376-12c8ab7fb75b?auto=format&fit=crop&q=80&w=800"
    ]
  },
  {
    id: "PJ-PROP-201",
    title: "MM Corporate Park High-Street",
    location: "MM Road, Shilphata, Navi Mumbai Side",
    bhk: 0,
    type: "Ready to Move",
    price: "₹45,000 / month",
    priceNumeric: 45000,
    carpetArea: "550 Sq.Ft - 800 Sq.Ft",
    sizeSqFt: 620,
    brokerage: "0%",
    paymentPlan: "Monthly Automated Renting",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=600",
    tag: "High Rental Demand Location",
    highlights: ["Frontline Main Road Display Window", "Central Variable AC System Installed", "Committed Multi-Level Heavy Parking", "24/7 Gated Corporate Precinct Security", "Fully Certified Occupancy Status (OC)"],
    purpose: "Rent",
    propertyType: "Commercial",
    bathrooms: 1,
    furnishing: "Furnished",
    buildingType: "Building",
    floorLevel: "Low",
    viewType: "City",
    rentalFrequency: "Monthly",
    paymentTerms: "4 Cheques",
    availability: "Ready",
    verified: true,
    featured: true,
    description: "Premium grade commercial showroom area with dynamic main-road frontage and fully finished designer workstations.",
    detailedDescription: "Positioned directly along the high-traffic Shilphata Junction, this commercial workspace provides the ultimate business visibility. Serves as a perfect ready-to-operate hub for medical clinics, high-end corporate agencies, or premium retail showrooms looking to launch with immediate effect.",
    amenities: ["Parking", "Central AC", "Security", "Power Backup", "Conference Room", "Server Enclosure"],
    floorPlanImage: "https://images.unsplash.com/photo-1545464693-f1798a373343?auto=format&fit=crop&q=80&w=600",
    brochureUrl: "#download-brochure-pdf",
    titleDeedUrl: "#view-title-deed-verification",
    agentName: "Rajesh K. Sharma",
    agentRole: "Commercial Specialist",
    agentPhone: "+91 86686 44479",
    agentEmail: "rajesh@propertyjunction.co",
    agentWhatsApp: "https://wa.me/918668644479?text=Hi%20Rajesh,%20I%20am%20interested%20in%20MM%20Corporate%20Park%20(PJ-PROP-201)",
    agentPhoto: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&q=80&w=400",
    gallery: [
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=800"
    ]
  },
  {
    id: "PJ-PROP-202",
    title: "Kharghar Oasis Penthouse Retreat",
    location: "Sector 12, Kharghar Bypass, Navi Mumbai",
    bhk: 4,
    type: "Ready to Move",
    price: "₹1.20 Lakhs / month",
    priceNumeric: 120000,
    carpetArea: "2,400 Sq.Ft - 2,850 Sq.Ft",
    sizeSqFt: 2600,
    brokerage: "0%",
    paymentPlan: "6 Cheques Term Plan",
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80&w=600",
    tag: "High Value Premium Rental",
    highlights: ["Double Spaced Living Area Rooftop Balcony", "Central Fully Equipped Kitchen Systems", "Next to Scenic Kharghar Bypass Parks", "No Agent commission charges applicable", "3 Private Covered Car Spaces"],
    purpose: "Rent",
    propertyType: "Apartment",
    bathrooms: 4,
    furnishing: "Furnished",
    buildingType: "Building",
    floorLevel: "High",
    viewType: "Garden",
    rentalFrequency: "Monthly",
    paymentTerms: "6 Cheques",
    availability: "Available",
    verified: true,
    featured: true,
    description: "A gorgeous luxury penthouse to lease under zero brokerage, perfect for high-net-worth expat living in Mumbai region.",
    detailedDescription: "Designed to provide a high-end luxury villa ambiance high above the clouds, this exclusive penthouse is a dream. Featuring breathtaking panoramic views, custom oak furnishings, top appliances, and custom marble floors.",
    amenities: ["Parking", "Balcony", "Central AC", "Gym", "Pool", "Security", "Rooftop Deck", "Elite Living Lounge", "Billiard Lounge"],
    floorPlanImage: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&q=80&w=600",
    brochureUrl: "#download-brochure-pdf",
    titleDeedUrl: "#view-title-deed-verification",
    agentName: "Aarti S. Mehta",
    agentRole: "Exclusive Portfolio Advisor",
    agentPhone: "+91 86686 44479",
    agentEmail: "aarti@propertyjunction.co",
    agentWhatsApp: "https://wa.me/918668644479?text=Hi%20Aarti,%20I%20am%20interested%20in%20Kharghar%20Oasis%20Penthouse%20(PJ-PROP-202)",
    agentPhoto: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400",
    gallery: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&q=80&w=800"
    ]
  }
];

export const propertyCatalog: Property[] = [];

// Initialize catalog with localStorage if available or use the defaults
if (typeof window !== 'undefined') {
  const saved = localStorage.getItem('property_junction_properties');
  if (saved) {
    try {
      const parsed = JSON.parse(saved);
      propertyCatalog.push(...parsed);
    } catch (e) {
      console.error("Error parsing properties", e);
      propertyCatalog.push(...defaultCatalog);
    }
  } else {
    localStorage.setItem('property_junction_properties', JSON.stringify(defaultCatalog));
    propertyCatalog.push(...defaultCatalog);
  }
} else {
  propertyCatalog.push(...defaultCatalog);
}

export function saveCatalogToLocalStorage(newCatalog: Property[]) {
  if (typeof window !== 'undefined') {
    localStorage.setItem('property_junction_properties', JSON.stringify(newCatalog));
  }
  propertyCatalog.splice(0, propertyCatalog.length, ...newCatalog);
}
